apiVersion: networking.cfargotunnel.com/v1alpha1
kind: TunnelBinding
metadata:
  name: nextjs-binding
  namespace: dockify-app
subjects:
- name: nextjs-service
spec:
  fqdn: main.dockify.app
  noTlsVerify: false
tunnelRef:
  kind: ClusterTunnel
  name: main-dockify-app-tunnel
---
apiVersion: v1
kind: Service
metadata:
  name: nextjs-public
  namespace: dockify-app
  labels:
    app: nextjs
    expose: cloudflare
  annotations:
    external-dns.alpha.kubernetes.io/hostname: main.dockify.app
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
spec:
  type: ClusterIP
  selector:
    app: nextjs
  ports:
  - name: http
    port: 80
    targetPort: 3000
    protocol: TCP
